### ISSUE TITLE
Is this thread safe?

### ISSUE THREAD

**Issue by josejulio** [rubenvp8510/websocket-client#3]
We should make it thread safe if isn't

**Comment by rubenvp8510** [comment]
What do you mean?

**Comment by josejulio** [comment]
Can we use the client from multiple threads without any problems? I mean, it possibly is because you are not saving any state as far i could see (apart from `set_headers`, but I guess that's meant to only be set at prior to connection)

**Comment by rubenvp8510** [comment]
I think is not thread safe use any sync method because if you use it on multiple threads you won't be able to identify which message belongs to which thread.
